[package]
name = "napi-current-env"
version = "0.1.0"
edition = "2024"

[dependencies]
napi = { version = "3.8.2", features = ["napi9", "tokio"] }
tokio = "1.49.0"

[dev-dependencies]
napi-derive = "3.5.1"
