[package]
name = "napi-current-env"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["examples/*"]

[dependencies]
napi = { version = "3.8.2", features = ["tokio"] }
tokio = "1.49.0"

[dev-dependencies]
fs-err = "3.2.2"
napi-derive = "3.5.1"
